services:
  #--- Nginx Reverse proxy ---
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - ./nginx/crt:/etc/nginx/certs:ro
    depends_on:
      - public
      - admin
      - api
      - minio
    networks:
      - internal

  # --- CertBot ---
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - internal

  # --- MySQL Database ---
  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  # --- postgresDb Storage ---
  postgres:
    image: postgres:16-alpine
    container_name: db
    restart: always
    env_file:
      - ./postgres/.env # Create this folder/file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- FastAPI Backend ---
  api:
    build:
      context: ./api.primeMedia.com
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./api.primeMedia.com/.env
    # ports:
    #   - "8000:8000" # internal; can be proxied later
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    #   minio:
    #     condition: service_healthy
    networks:
      - internal
    restart: always

  # --- Public Next.js ---
  public:
    build:
      context: ./primeMedia.com
      dockerfile: Dockerfile
    container_name: public
    env_file:
      - ./primeMedia.com/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - internal
    restart: always

  # --- Admin Next.js ---
  admin:
    build:
      context: ./cms.primeMedia.com
      dockerfile: Dockerfile
    container_name: admin
    env_file:
      - ./cms.primeMedia.com/.env
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - api
    networks:
      - internal
    restart: always

# --- Volumes ---
volumes:
  mysql_data:
    name: news_mysql_data
  postgres_data:
    name: news_postgres_data
  minio_data:
    name: news_minio_data

# --- Networks ---
networks:
  internal:
    driver: bridge
