services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: dailytimes-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SERVER_ENVIRONMENT=production
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_DBNAME=dailytimes
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=guest
  #     - RABBITMQ_PASSWORD=guest
  #   depends_on:
  #     - postgres
  #     - redis
  #     - rabbitmq
  #   networks:
  #     - dailytimes-network
  #   restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: dailytimes-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/pg-init:/docker-entrypoint-initdb.d
    networks:
      - dailytimes-network
    restart: unless-stopped

  # --- MinIO Object Storage ---
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - ./.env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web console
    volumes:
      - minio_data:/data
    networks:
      - dailytimes-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: dailytimes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dailytimes-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dailytimes-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - "./.env"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - dailytimes-network
    restart: unless-stopped

networks:
  dailytimes-network:
    driver: bridge

volumes:
  postgres-data:
  minio_data:
  redis-data:
  rabbitmq-data:
