export const dynamic = 'force-dynamic';

import Header from './components/Header';
import CategoryGrid from './components/CategoryGrid';
import Footer from "./components/Footer";
import TranslationProvider from './components/TranslationProvider';
import {fetchCategories} from './lib/fetch';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "news App",
  description: "Generated by create news app",
};


export default async function RootLayout({ children }) {
  const [categories] = await Promise.all([
    fetchCategories(),
  ]);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TranslationProvider>
            <Header sections={categories} />
            <main>
              {children}
            </main>
            <CategoryGrid categories={categories} />
            <Footer />
        </TranslationProvider>
      </body>
    </html>
  );
}
