'use client';
import { SearchProvider } from './components/SearchBar';
import { Geist, Geist_Mono } from "next/font/google";
import Header from './components/Header';
import Footer from "./components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "news App",
  description: "Generated by create news app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <SearchProvider>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
      </SearchProvider>
      </body>
    </html>
  );
}